spring.application.name=products-service
server.port=8082
management.endpoints.web.exposure.include=health
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/products_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.table=flyway_schema_history_products